# 02/08/89/jos - Changed LCLBINDIR from /ds/bin to ~/bin .
# 02/08/89/jos - Changed LOCAL_APP_DIR from /ds/apps to ~/apps .
# 02/25/89/jos - INSTALL_ROOT from ${DSTROOT}/bootdisk/NeXT/Unix to ${DSTROOT}
#		 DSP_ROOT from ${DSTROOT}/bootdisk/NeXT/System/DSPFiles
#		  	    to ${DSTROOT}/usr/lib/dsp
#		 DSPDEMODIR from ${DSTROOT}/bootdisk/Programming/Demos
#		 	    to   ${DSTROOT}/NextDeveloper/Demos
# 		DSP_INSTALL_ROOT from ${SRCROOT}/bootdisk/NeXT/Unix/usr/src/dsp
# 			    to ${DSTROOT}/usr/lib/dsp
#		DSP_MUSIC_DIR from ${DSTROOT}/bootdisk/Sounds/DSP
#				to ${DSTROOT}/NextLibrary/Sounds/DSP
#		DSP_AP_IMG_DIR from $(SMSRC_DIR)/imgap to ${SRCROOT}/imgap
# 03/06/89/jos - Added INTERNAL_BIN_DIR (for sim56000 installation)
# 03/06/89/jos - Added BOOT_BIN_DIR (for dsp/bin/*.boot installation)
# 03/25/89/jos - Changed ${SRCROOT} to ${SRCROOT}/dsp

# *** These filenames must stay in synch with those in $DSP/src/lib/dsp.h ***

PRODUCT_DEPENDENCIES = $(LOCAL_DSP_INSTALL_ROOT)/lib/libdsp_g.a

INSTALL_ROOT = ${DSTROOT}

LOCAL_DSP_INSTALL_ROOT = $(HOME)/dsp_proj/dsp
DSP_INSTALL_ROOT = ${DSTROOT}/usr/lib/dsp
# Change DSP_ROOT to DSP_INSTALL_ROOT in make.bag (eg apsrc)
DSP_ROOT = ${DSTROOT}/usr/lib/dsp

SOURCE_DIR = ${SRCROOT}/$(NAME)
BIN_SOURCE_DIR = ${SRCROOT}/src/bin
TOOL_SOURCE_DIR = ${SRCROOT}/tools

# Change to DSP_SYSTEM_INSTALL_DIR:
SYSTEMDIR = $(DSP_INSTALL_ROOT)/monitor
LOCAL_DSP_SYSTEM_DIR = $(LOCAL_DSP_INSTALL_ROOT)/monitor

LOCAL_APP_DIR = $(LOCAL_DSP_INSTALL_ROOT)/bin/apps
LCLBINDIR = $(LOCAL_DSP_INSTALL_ROOT)/bin
BINDIR = $(INSTALL_ROOT)/usr/bin

INTERNAL_BIN_DIR = $(LCLBINDIR)
BOOT_BIN_DIR_BIN = ../../../bin
BOOT_BIN_DIR = ../bin

DSPDEMODIR = ${DSTROOT}/NextDeveloper/Demos

# where project release notes are to be installed
# RELNOTES_DIR = ${DSTROOT}/usr/local/RelNotes
# RELNOTES_DIR = ${DSTROOT}/usr/local/doc/music_proj/notes
RELNOTES_DIR = ${DSTROOT}/NextLibrary/Documentation/NextDev/ReleaseNotes

# where man pages are to be installed
# MAN_DIR = ${DSTROOT}/usr/local/doc/music_proj/man
MAN_DIR = ${DSTROOT}/usr/man/man1
LOCAL_MAN_DIR = $(LOCAL_DSP_INSTALL_ROOT)/man

# ~dsp/doc
DOC_DIR = $(SRCROOT)/$(NAME)
DOC_INSTALL_DIR = $(DSP_INSTALL_ROOT)/$(NAME)

# *** NOTE *** SMSRC_DIR MUST AGREE WITH THE -I DIR IN dspasm-run
#/* for installsrc */
SMSRC_DIR = ${SRCROOT}/smsrc
#/* for make install */
SMSRC_INSTALL_DIR = $(DSP_INSTALL_ROOT)/smsrc
# used for dspasmal.local in bin/dspasm/Makefile
LOCAL_SMSRC_DIR = $(LOCAL_DSP_INSTALL_ROOT)/smsrc/

DSP_MUSIC_DIR = ${DSTROOT}/NextLibrary/Sounds/DSP
DSP_MUSIC_SRC_DIR = ${SRCROOT}/img

### DSP_AP_IMG_DIR = ${SRCROOT}/imgap
# cf. dsptestap Makefile:
LOCAL_DSP_AP_IMG_DIR = $(LOCAL_DSP_INSTALL_ROOT)/imgap

M_PRODUCT_DIR = $(DSPDEMODIR)/$(PRODUCT).app
LOCAL_M_PRODUCT_DIR = $(LOCAL_APP_DIR)/$(PRODUCT).app

LIBDSP_SRC_DIR = ${SRCROOT}/src/lib
# directories for library Makefile (currently NAME=dsp)
LIB_DIR = $(INSTALL_ROOT)/usr/lib/$(NAME)
LIBA_DIR = $(INSTALL_ROOT)/usr/lib
INC_DIR = $(INSTALL_ROOT)/usr/include
SHLIBDIR = $(INSTALL_ROOT)/usr/shlib
PSLIB_DIR = $(INSTALL_ROOT)/usr/lib/ps/packages/$(NAME)
SPEC_DIR = $(INSTALL_ROOT)/usr/doc/NeXT/SysRefNotes/SpecSheets/$(NAME)
AUX_DIR = $(INSTALL_ROOT)/usr/lib/spec/$(NAME)

# flags for install
IFLAGS = -q -c
BINIFLAGS = -s

${SRCROOT}/bin ${SRCROOT} $(BIN_SOURCE_DIR) $(BINDIR) $(SYSTEMDIR) $(DSPDEMODIR) $(DSP_MUSIC_DIR) $(DSP_MUSIC_SRC_DIR) $(LCLBINDIR) $(INC_DIR) $(DSTROOT) $(DSP_INSTALL_ROOT)/$(NAME) $(SOURCE_DIR) $(MAN_DIR) $(RELNOTES_DIR) $(BIN_SOURCE_DIR)/$(NAME) $(TOOL_SOURCE_DIR)/$(NAME) $(BOOT_BIN_DIR_BIN) $(LIBA_DIR) $(SHLIBDIR):
	mkdirs -m 755 $@

$(LCLBINDIR)/$(PRODUCT): $(LCLBINDIR)
	/bin/rm -f $(LCLBINDIR)/$(PRODUCT)
	ln -s `pwd`/$(PRODUCT) $(LCLBINDIR)

.SUFFIXES: .o .c .f .s .dsp .img .asm .lod .lnk .snd

.lod.dsp:
	$(LCLBINDIR)/dspimg $*.lod $@

# Note that the if is always "true" below.

.asm.dsp: ../../smsrc/mkmon8k.dsp
	if $(LCLBINDIR)/dspasmal $*.asm; then \
		$(LCLBINDIR)/dspimg $*.lod $@ ; else /bin/rm $*.lod ; fi

.asm.lod: ../../smsrc/mkmon8k.dsp
	$(LCLBINDIR)/dspasmal $*.asm 

.asm.img: ../../smsrc/mkmon8k.dsp
	$(LCLBINDIR)/dspasmal $*.asm
	$(LCLBINDIR)/dspimg $*.lod $*.img

.lod.snd:
	sndconvert -m -s44100 $*.lod

.asm.snd: ../../smsrc/mkmon8k.dsp
	$(LCLBINDIR)/dspasmal $*.asm 
	sndconvert -m -s44100 $*.lod

../../smsrc/mkmon8k.dsp: 
	(cd ../../smsrc ; make mkmon8k.dsp)

