/* This source file was auto-generated by dspwrap from dsp macro asymp.
   It is included by unit generator AsympUG. It should not be edited.*/
#import <musickit/UnitGenerator.h>

static MKMasterUGStruct _masterUGStruct = {
   4 /* nArgs */,
   {0,2,0,0,1,0,0,1,0,0,0,0,0} /* globalSymCount */,
   {1,0,0} /* fixupCount */
};

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+initialize  /* Sent once on class start-up. */
{
#  define OFFSET(_x) _x.value.i
   static DSPSymbol _argSymbols[4];
   static DSPSymbol _symbolsX[] = {
      {DSP_LC_X,"orch_asymp_1_aout","GRI"},
      {DSP_LC_X,"orch_asymp_1_trg","GRI"}
   };
   static DSPSymbol _symbolsY[] = {
      {DSP_LC_Y,"orch_asymp_1_rate","GRI"}
   };
   static DSPSymbol _symbolsL[] = {
      {DSP_LC_L,"orch_asymp_1_amp","GRI"}
   };
   _masterUGStruct.symbols[(int)DSP_LC_X] = _symbolsX;
   _masterUGStruct.symbols[(int)DSP_LC_Y] = _symbolsY;
   _masterUGStruct.symbols[(int)DSP_LC_L] = _symbolsL;
   OFFSET(_symbolsX[0]) = 0;
   OFFSET(_symbolsX[1]) = 1;
   OFFSET(_symbolsY[0]) = 0;
   OFFSET(_symbolsL[0]) = 0;
   _argSymbols[(int)aout] = _symbolsX[0];
   _argSymbols[(int)trg] = _symbolsX[1];
   _argSymbols[(int)rate] = _symbolsY[0];
   _argSymbols[(int)amp] = _symbolsL[0];
   _masterUGStruct.argSymbols = _argSymbols;
   return self;
}
