/* This class was auto-generated by dspwrap from macro dswitch. 
   It should not be edited. */

#import "DswitchUGxx.h"

@implementation DswitchUGxx : DswitchUG

/* times in seconds/sample */
#define COMPUTETIME (160 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))
#define OFFCHIP_COMPUTETIME (274 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))

static MKLeafUGStruct _leafUGStruct = {
    {2/* xArg  */,  3/* yArg  */,  0/* lArg */,
     18/* pLoop */,  0/* pSubr */,
     0/* xData */,  0/* yData */} /* memory requirements */, COMPUTETIME};

+(MKLeafUGStruct *)classInfo  
{   if (_leafUGStruct.master == NULL)
      _leafUGStruct.master = [self masterUGPtr];
    return &_leafUGStruct; }

+initialize /* Sent once on factory start-up. */
{
enum args { i1adr, scale1, aout, i2adr, switchdelay };
   static DSPMemorySpace _argSpaces[] = {DSP_MS_X,DSP_MS_N,DSP_MS_X,DSP_MS_X,DSP_MS_N};
   static DSPDataRecord _dataRecP = {NULL, DSP_LC_P, 0, 1, 18}; 
   static int _dataP[] = {0x61d800,0x6ddc00,0x6edc00,0xc79800,0x47f400,
                          0x1,0x56fe00,0x44d900,0x61080,0x8d,
                          0x565ea1,0x44d900,0x46dd7c,0x29050,0x565e00,
                          0x24000b,0x2f048,0x5f5c00};
   static DSPFixup _fixupsP[] = {
   {DSP_LC_P, NULL, 1 /* decrement */, 9 /* refOffset */,  13 /* relAddress */}
   };
   _leafUGStruct.master = NULL;
   _leafUGStruct.argSpaces = _argSpaces;
   _leafUGStruct.data[(int)DSP_LC_P] = &_dataRecP;
   _dataRecP.data = _dataP;
   _leafUGStruct.fixups[(int)DSP_LC_P - (int)DSP_LC_P_BASE] = _fixupsP;
   MKInitUnitGeneratorClass(&_leafUGStruct);
   _leafUGStruct.reserved1 = MK_2COMPUTETIMES;
   _leafUGStruct.offChipComputeTime = OFFCHIP_COMPUTETIME;
   return self;
}
@end
