/* This source file was auto-generated by dspwrap from dsp macro dswitcht.
   It is included by unit generator DswitchtUG. It should not be edited.*/
#import <musickit/UnitGenerator.h>

static MKMasterUGStruct _masterUGStruct = {
   6 /* nArgs */,
   {0,3,0,0,3,0,0,0,0,0,0,0,0} /* globalSymCount */,
   {1,0,0} /* fixupCount */
};

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+initialize  /* Sent once on class start-up. */
{
#  define OFFSET(_x) _x.value.i
   static DSPSymbol _argSymbols[6];
   static DSPSymbol _symbolsX[] = {
      {DSP_LC_X,"orch_dswitcht_1_i1adr","GRI"},
      {DSP_LC_X,"orch_dswitcht_1_scale1","GRI"},
      {DSP_LC_X,"orch_dswitcht_1_scale2","GRI"}
   };
   static DSPSymbol _symbolsY[] = {
      {DSP_LC_Y,"orch_dswitcht_1_aout","GRI"},
      {DSP_LC_Y,"orch_dswitcht_1_i2adr","GRI"},
      {DSP_LC_Y,"orch_dswitcht_1_tickdelay","GRI"}
   };
   _masterUGStruct.symbols[(int)DSP_LC_X] = _symbolsX;
   _masterUGStruct.symbols[(int)DSP_LC_Y] = _symbolsY;
   OFFSET(_symbolsX[0]) = 2;
   OFFSET(_symbolsX[1]) = 0;
   OFFSET(_symbolsX[2]) = 1;
   OFFSET(_symbolsY[0]) = 1;
   OFFSET(_symbolsY[1]) = 2;
   OFFSET(_symbolsY[2]) = 0;
   _argSymbols[(int)i1adr] = _symbolsX[0];
   _argSymbols[(int)scale1] = _symbolsX[1];
   _argSymbols[(int)scale2] = _symbolsX[2];
   _argSymbols[(int)aout] = _symbolsY[0];
   _argSymbols[(int)i2adr] = _symbolsY[1];
   _argSymbols[(int)tickdelay] = _symbolsY[2];
   _masterUGStruct.argSymbols = _argSymbols;
   return self;
}
