/* This source file was auto-generated by dspwrap from dsp macro mul2.
   It is included by unit generator Mul2UG. It should not be edited.*/
#import <musickit/UnitGenerator.h>

static MKMasterUGStruct _masterUGStruct = {
   3 /* nArgs */,
   {0,1,0,0,2,0,0,0,0,0,0,0,0} /* globalSymCount */,
   {1,0,0} /* fixupCount */
};

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+initialize  /* Sent once on class start-up. */
{
#  define OFFSET(_x) _x.value.i
   static DSPSymbol _argSymbols[3];
   static DSPSymbol _symbolsX[] = {
      {DSP_LC_X,"orch_mul2_1_i1adr","GRI"}
   };
   static DSPSymbol _symbolsY[] = {
      {DSP_LC_Y,"orch_mul2_1_aout","GRI"},
      {DSP_LC_Y,"orch_mul2_1_i2adr","GRI"}
   };
   _masterUGStruct.symbols[(int)DSP_LC_X] = _symbolsX;
   _masterUGStruct.symbols[(int)DSP_LC_Y] = _symbolsY;
   OFFSET(_symbolsX[0]) = 0;
   OFFSET(_symbolsY[0]) = 1;
   OFFSET(_symbolsY[1]) = 0;
   _argSymbols[(int)i1adr] = _symbolsX[0];
   _argSymbols[(int)aout] = _symbolsY[0];
   _argSymbols[(int)i2adr] = _symbolsY[1];
   _masterUGStruct.argSymbols = _argSymbols;
   return self;
}
