/* This source file was auto-generated by dspwrap from dsp macro oscg.
   It is included by unit generator OscgUG. It should not be edited.*/
#import <musickit/UnitGenerator.h>

static MKMasterUGStruct _masterUGStruct = {
   6 /* nArgs */,
   {0,2,0,0,2,0,0,2,0,0,0,0,0} /* globalSymCount */,
   {1,0,0} /* fixupCount */
};

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+initialize  /* Sent once on class start-up. */
{
#  define OFFSET(_x) _x.value.i
   static DSPSymbol _argSymbols[6];
   static DSPSymbol _symbolsX[] = {
      {DSP_LC_X,"orch_oscg_1_atab","GRI"},
      {DSP_LC_X,"orch_oscg_1_mtab","GRI"}
   };
   static DSPSymbol _symbolsY[] = {
      {DSP_LC_Y,"orch_oscg_1_amp","GRI"},
      {DSP_LC_Y,"orch_oscg_1_aout","GRI"}
   };
   static DSPSymbol _symbolsL[] = {
      {DSP_LC_L,"orch_oscg_1_inc","GRI"},
      {DSP_LC_L,"orch_oscg_1_phs","GRI"}
   };
   _masterUGStruct.symbols[(int)DSP_LC_X] = _symbolsX;
   _masterUGStruct.symbols[(int)DSP_LC_Y] = _symbolsY;
   _masterUGStruct.symbols[(int)DSP_LC_L] = _symbolsL;
   OFFSET(_symbolsX[0]) = 0;
   OFFSET(_symbolsX[1]) = 1;
   OFFSET(_symbolsY[0]) = 1;
   OFFSET(_symbolsY[1]) = 0;
   OFFSET(_symbolsL[0]) = 0;
   OFFSET(_symbolsL[1]) = 1;
   _argSymbols[(int)atab] = _symbolsX[0];
   _argSymbols[(int)mtab] = _symbolsX[1];
   _argSymbols[(int)amp] = _symbolsY[0];
   _argSymbols[(int)aout] = _symbolsY[1];
   _argSymbols[(int)inc] = _symbolsL[0];
   _argSymbols[(int)phs] = _symbolsL[1];
   _masterUGStruct.argSymbols = _argSymbols;
   return self;
}
