/* This source file was auto-generated by dspwrap from dsp macro oscgaf.
   It is included by unit generator OscgafUG. It should not be edited.*/
#import <musickit/UnitGenerator.h>

static MKMasterUGStruct _masterUGStruct = {
   7 /* nArgs */,
   {0,3,0,0,3,0,0,1,0,0,0,0,0} /* globalSymCount */,
   {1,0,0} /* fixupCount */
};

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+initialize  /* Sent once on class start-up. */
{
#  define OFFSET(_x) _x.value.i
   static DSPSymbol _argSymbols[7];
   static DSPSymbol _symbolsX[] = {
      {DSP_LC_X,"orch_oscgaf_1_aina","GRI"},
      {DSP_LC_X,"orch_oscgaf_1_atab","GRI"},
      {DSP_LC_X,"orch_oscgaf_1_inc","GRI"}
   };
   static DSPSymbol _symbolsY[] = {
      {DSP_LC_Y,"orch_oscgaf_1_ainf","GRI"},
      {DSP_LC_Y,"orch_oscgaf_1_aout","GRI"},
      {DSP_LC_Y,"orch_oscgaf_1_mtab","GRI"}
   };
   static DSPSymbol _symbolsL[] = {
      {DSP_LC_L,"orch_oscgaf_1_phs","GRI"}
   };
   _masterUGStruct.symbols[(int)DSP_LC_X] = _symbolsX;
   _masterUGStruct.symbols[(int)DSP_LC_Y] = _symbolsY;
   _masterUGStruct.symbols[(int)DSP_LC_L] = _symbolsL;
   OFFSET(_symbolsX[0]) = 2;
   OFFSET(_symbolsX[1]) = 0;
   OFFSET(_symbolsX[2]) = 1;
   OFFSET(_symbolsY[0]) = 1;
   OFFSET(_symbolsY[1]) = 0;
   OFFSET(_symbolsY[2]) = 2;
   OFFSET(_symbolsL[0]) = 0;
   _argSymbols[(int)aina] = _symbolsX[0];
   _argSymbols[(int)atab] = _symbolsX[1];
   _argSymbols[(int)inc] = _symbolsX[2];
   _argSymbols[(int)ainf] = _symbolsY[0];
   _argSymbols[(int)aout] = _symbolsY[1];
   _argSymbols[(int)mtab] = _symbolsY[2];
   _argSymbols[(int)phs] = _symbolsL[0];
   _masterUGStruct.argSymbols = _argSymbols;
   return self;
}
