/* This class was auto-generated by dspwrap from macro out1b. 
   It should not be edited. */

#import "Out1bUGx.h"

@implementation Out1bUGx : Out1bUG

/* times in seconds/sample */
#define COMPUTETIME (130 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))
#define OFFCHIP_COMPUTETIME (206 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))

static MKLeafUGStruct _leafUGStruct = {
    {1/* xArg  */,  1/* yArg  */,  0/* lArg */,
     16/* pLoop */,  0/* pSubr */,
     0/* xData */,  0/* yData */} /* memory requirements */, COMPUTETIME};

+(MKLeafUGStruct *)classInfo  
{   if (_leafUGStruct.master == NULL)
      _leafUGStruct.master = [self masterUGPtr];
    return &_leafUGStruct; }

+initialize /* Sent once on factory start-up. */
{
enum args { sclB, iadr };
   static DSPMemorySpace _argSpaces[] = {DSP_MS_N,DSP_MS_X};
   static DSPDataRecord _dataRecP = {NULL, DSP_LC_P, 0, 1, 16}; 
   static int _dataP[] = {0x45d800,0x7f095,0x3fea,0x69dc00,0x66e500,
                          0x5f426,0x3ff,0x3e0200,0x4fde00,0xc2d900,
                          0x61080,0x8d,0x4feea3,0x92d971,0x5f426,
                          0xffffff};
   static DSPFixup _fixupsP[] = {
   {DSP_LC_P, NULL, 1 /* decrement */, 11 /* refOffset */,  13 /* relAddress */}
   };
   _leafUGStruct.master = NULL;
   _leafUGStruct.argSpaces = _argSpaces;
   _leafUGStruct.data[(int)DSP_LC_P] = &_dataRecP;
   _dataRecP.data = _dataP;
   _leafUGStruct.fixups[(int)DSP_LC_P - (int)DSP_LC_P_BASE] = _fixupsP;
   MKInitUnitGeneratorClass(&_leafUGStruct);
   _leafUGStruct.reserved1 = MK_2COMPUTETIMES;
   _leafUGStruct.offChipComputeTime = OFFCHIP_COMPUTETIME;
   return self;
}
@end
