/* This source file was auto-generated by dspwrap from dsp macro out2sum.
   It is included by unit generator Out2sumUG. It should not be edited.*/
#import <musickit/UnitGenerator.h>

static MKMasterUGStruct _masterUGStruct = {
   3 /* nArgs */,
   {0,1,0,0,2,0,0,0,0,0,0,0,0} /* globalSymCount */,
   {1,0,0} /* fixupCount */
};

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+initialize  /* Sent once on class start-up. */
{
#  define OFFSET(_x) _x.value.i
   static DSPSymbol _argSymbols[3];
   static DSPSymbol _symbolsX[] = {
      {DSP_LC_X,"orch_out2sum_1_sclA","GRI"}
   };
   static DSPSymbol _symbolsY[] = {
      {DSP_LC_Y,"orch_out2sum_1_iadr","GRI"},
      {DSP_LC_Y,"orch_out2sum_1_sclB","GRI"}
   };
   _masterUGStruct.symbols[(int)DSP_LC_X] = _symbolsX;
   _masterUGStruct.symbols[(int)DSP_LC_Y] = _symbolsY;
   OFFSET(_symbolsX[0]) = 0;
   OFFSET(_symbolsY[0]) = 1;
   OFFSET(_symbolsY[1]) = 0;
   _argSymbols[(int)sclA] = _symbolsX[0];
   _argSymbols[(int)iadr] = _symbolsY[0];
   _argSymbols[(int)sclB] = _symbolsY[1];
   _masterUGStruct.argSymbols = _argSymbols;
   return self;
}
