/* This class was auto-generated by dspwrap from macro scl1add2. 
   It should not be edited. */

#import "Scl1add2UGxyx.h"

@implementation Scl1add2UGxyx : Scl1add2UG

/* times in seconds/sample */
#define COMPUTETIME (114 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))
#define OFFCHIP_COMPUTETIME (188 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))

static MKLeafUGStruct _leafUGStruct = {
    {2/* xArg  */,  2/* yArg  */,  0/* lArg */,
     9/* pLoop */,  0/* pSubr */,
     0/* xData */,  0/* yData */} /* memory requirements */, COMPUTETIME};

+(MKLeafUGStruct *)classInfo  
{   if (_leafUGStruct.master == NULL)
      _leafUGStruct.master = [self masterUGPtr];
    return &_leafUGStruct; }

+initialize /* Sent once on factory start-up. */
{
enum args { i1adr, i1gin, aout, i2adr };
   static DSPMemorySpace _argSpaces[] = {DSP_MS_Y,DSP_MS_N,DSP_MS_X,DSP_MS_X};
   static DSPDataRecord _dataRecP = {NULL, DSP_LC_P, 0, 1, 9}; 
   static int _dataP[] = {0x61d800,0x47d800,0x6ddc00,0x6edc00,0xf8bd00,
                          0x61080,0x88,0xf0bdb3,0x565e41};
   static DSPFixup _fixupsP[] = {
   {DSP_LC_P, NULL, 1 /* decrement */, 6 /* refOffset */,  8 /* relAddress */}
   };
   _leafUGStruct.master = NULL;
   _leafUGStruct.argSpaces = _argSpaces;
   _leafUGStruct.data[(int)DSP_LC_P] = &_dataRecP;
   _dataRecP.data = _dataP;
   _leafUGStruct.fixups[(int)DSP_LC_P - (int)DSP_LC_P_BASE] = _fixupsP;
   MKInitUnitGeneratorClass(&_leafUGStruct);
   _leafUGStruct.reserved1 = MK_2COMPUTETIMES;
   _leafUGStruct.offChipComputeTime = OFFCHIP_COMPUTETIME;
   return self;
}
@end
