/* This class was auto-generated by dspwrap from macro scl2add2. 
   It should not be edited. */

#import "Scl2add2UGyyx.h"

@implementation Scl2add2UGyyx : Scl2add2UG

/* times in seconds/sample */
#define COMPUTETIME (116 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))
#define OFFCHIP_COMPUTETIME (224 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK))

static MKLeafUGStruct _leafUGStruct = {
    {2/* xArg  */,  3/* yArg  */,  0/* lArg */,
     11/* pLoop */,  0/* pSubr */,
     0/* xData */,  0/* yData */} /* memory requirements */, COMPUTETIME};

+(MKLeafUGStruct *)classInfo  
{   if (_leafUGStruct.master == NULL)
      _leafUGStruct.master = [self masterUGPtr];
    return &_leafUGStruct; }

+initialize /* Sent once on factory start-up. */
{
enum args { i1adr, i1gin, aout, i2adr, i2gin };
   static DSPMemorySpace _argSpaces[] = {DSP_MS_Y,DSP_MS_N,DSP_MS_Y,DSP_MS_X,DSP_MS_N};
   static DSPDataRecord _dataRecP = {NULL, DSP_LC_P, 0, 1, 11}; 
   static int _dataP[] = {0x61d800,0x6ddc00,0xf59800,0x6edc00,0x4cd900,
                          0x46dda0,0x61080,0x8a,0x4cd9b3,0x46dd00,
                          0x5e5ea0};
   static DSPFixup _fixupsP[] = {
   {DSP_LC_P, NULL, 1 /* decrement */, 7 /* refOffset */,  10 /* relAddress */}
   };
   _leafUGStruct.master = NULL;
   _leafUGStruct.argSpaces = _argSpaces;
   _leafUGStruct.data[(int)DSP_LC_P] = &_dataRecP;
   _dataRecP.data = _dataP;
   _leafUGStruct.fixups[(int)DSP_LC_P - (int)DSP_LC_P_BASE] = _fixupsP;
   MKInitUnitGeneratorClass(&_leafUGStruct);
   _leafUGStruct.reserved1 = MK_2COMPUTETIMES;
   _leafUGStruct.offChipComputeTime = OFFCHIP_COMPUTETIME;
   return self;
}
@end
