| Modification history:
| 	3 aug/daj - Added bcopy and fixdfsi
|
| These pointers are declared in pointers.c.  They get filled in with a #init
| from the library specification file with the real values of their symbols.
| They are used here to make an indirect jmp to these routines.
.globl __libmusic_objc_msgSend
.globl __libmusic_objc_msgSendSuper
.globl __libmusic_objc_getClass
.globl __libmusic_objc_getMetaClass
.globl __libmusic__fixunsdfsi
.globl __libmusic__fixdfsi
.globl __libmusic_bcopy


| These are the routines to make the indirect jumps.   These are needed because
| they can't be substituted by cpp (because they are generated by the compiler
| directly).   To use these routines the music link editor function of aliasing
| a symbol to  another symbol is used.  So the symbols like _objc_msgSend
| are aliased to .libmusic_objc_msgSend etc. all the calls to them get
| relocated to their aliases.  The real symbols (_objc_msgSend, etc) never
| appear in the target shared library.
	.text
.globl .libmusic_objc_msgSend
.libmusic_objc_msgSend:
	movel	__libmusic_objc_msgSend, a0
	jmp	a0@

.globl .libmusic_objc_msgSendSuper
.libmusic_objc_msgSendSuper:
	movel	__libmusic_objc_msgSendSuper, a0
	jmp	a0@

.globl .libmusic_objc_getClass
.libmusic_objc_getClass:
	movel	__libmusic_objc_getClass, a0
	jmp	a0@

.globl .libmusic_objc_getMetaClass
.libmusic_objc_getMetaClass:
	movel	__libmusic_objc_getMetaClass, a0
	jmp	a0@

.globl .libmusic__fixunsdfsi
.libmusic__fixunsdfsi:
	movel	__libmusic__fixunsdfsi, a0
	jmp	a0@

.globl .libmusic__fixdfsi
.libmusic__fixdfsi:
	 movel	__libmusic__fixdfsi, a0
	jmp	a0@

.globl .libmusic_bcopy
.libmusic_bcopy:
	 movel	__libmusic_bcopy, a0
	jmp	a0@

