/* 
    dspwrap.h
    Copyright 1989, NeXT, Inc.
    
    This file is part of the Music Kit.
  */
/* The following is the UnitGenerator's interface with the MC56001. You
   never need to deal with these structures. They are generated automatically
   by the utility dspwrap. */

typedef struct _MKMasterUGStruct { /* Used by UnitGenerator "master" class. */
    unsigned argCount;             /* Number of arguments. */
    int symCount[DSP_LC_NUM];      /* Number of symbols loaded in each space.
                      Needed for symbols that are not args. */
    int fixupCount[DSP_LC_NUM_P];  /* Number of fixups in each P space */
    DSPSymbol *symbols[DSP_LC_NUM];/* Symbol list per DSP location ctr. */
    DSPSymbol *argSymbols;         /* Array of argument symbols. */
    void *reserved;                /* Reserved */ 
} MKMasterUGStruct;

typedef struct _MKLeafUGStruct {    /* Used by UnitGenerator "leaf" class. */
    MKOrchMemStruct reso;           /* Resources needed  */
    double computeTime;             /* Time for this unit generator to
                                       compute one sample, in seconds. */
    id **availLists;                /* Array of lists of idle patches,
                                       indexed by dsp number. */
    DSPDataRecord *data[DSP_LC_NUM];/* Sorted absolute data records */
    DSPFixup *fixups[DSP_LC_NUM_P]; /* Fix-up array for each P space */
    DSPMemorySpace *argSpaces;      /* Array which tells which space each
                                       argument points to. If the argument
                                       is not address-valued, the array value 
                                       here is DSP_MS_N. */
    MKMasterUGStruct *master;       /* Pointer to master UGStruct  */
    int reserved1;                  
    double offChipComputeTime;      /* Compute time when ug is off chip. */
    void *reserved2;
} MKLeafUGStruct;

extern void MKInitUnitGeneratorClass(MKLeafUGStruct *classInfo);
/* Unit Generator initialization (used in files generated by dspwrap). */

#define MK_2COMPUTETIMES 0x322e30   /* This is a magic number that signals
                                       we have 2 compute times, one for
                                       on-chip and one for off-chip. This
                                       feature is supported in the release 2.0
                                       dspwrap */


