/* This source file was auto-generated by dsploadwrap from dsp macro orchloopbegin.
   It is included by unit generator OrchloopbeginUG. It should not be edited.*/
#import <musickit/musickit.h>

static MKMasterUGStruct _masterUGStruct = {
   0 /* nArgs */,
   {0,0,0,0,0,0,0,0,0,0,0,0,0} /* globalSymCount */,
   {2,0,0} /* fixupCount */
};

#define COMPUTETIME (44 * (DSP_CLOCK_PERIOD / DSPMK_I_NTICK)) /* seconds per sample */

static MKLeafUGStruct _leafUGStruct = {
    {0/* xArg  */,  0/* yArg  */,  0/* lArg */,
     22/* pLoop */,  0/* pSubr */,
     0/* xData */,  0/* yData */} /* memory requirements */, COMPUTETIME};

+(MKLeafUGStruct *)classInfo  
{   if (_leafUGStruct.master == NULL)
      _leafUGStruct.master = [self masterUGPtr];
    return &_leafUGStruct; }

+(MKMasterUGStruct *)masterUGPtr { return &_masterUGStruct; }

+initialize /* Sent once on factory start-up. */
{   static DSPDataRecord _dataRecP = {NULL, DSP_LC_P, 0, 1, 22}; 
   static int _dataP[] = {0xaa9a3,0x80,0xb01b6,0x3fe8,0xa01c4,
                          0x88,0xbf080,0x3ff0,0xbf080,0x3ff8,
                          0x488200,0x498300,0x240010,0x2d040,0x480200,
                          0xfcb8,0x60f400,0x4,0x64f400,0x4,
                          0x32f600,0x0};
   static DSPFixup _fixupsP[] = {
   {DSP_LC_P, NULL, 0 /* decrement */, 1 /* refOffset */,  0 /* relAddress */}
   ,{DSP_LC_P, NULL, 0 /* decrement */, 5 /* refOffset */,  8 /* relAddress */}
   };
   _leafUGStruct.master = NULL;
   _leafUGStruct.data[(int)DSP_LC_P] = &_dataRecP;
   _dataRecP.data = _dataP;
   _leafUGStruct.fixups[(int)DSP_LC_P - (int)DSP_LC_P_BASE] = _fixupsP;
   MKInitUnitGeneratorClass(&_leafUGStruct);
   return self;
}

