| These pointers are declared in pointers.c.  They get filled in with a #init
| from the library specification file with the real values of their symbols.
| They are used here to make an indirect jmp to these routines.
.globl __libdsp_bcopy

| These are the routines to make the indirect jumps.   These are needed because
| they can't be substituted by cpp (because they are generated by the compiler
| directly).   To use these routines the link editor function of aliasing
| a symbol to  another symbol is used.  So the symbols like _bcopy are aliased
| to .libdsp_bcopy all the calls to them get relocated to their aliases.  The
| real symbols (_bcopy, etc) never appear in the target shared library.

.globl .libdsp_bcopy
.globl __libdsp__fixunsdfsi
.globl __libdsp__fixdfsi

.libdsp_bcopy:
	movel	__libdsp_bcopy, a0
	jmp	a0@

.globl .libdsp__fixunsdfsi
.libdsp__fixunsdfsi:
	movel	__libdsp__fixunsdfsi, a0
	jmp	a0@

.globl .libdsp__fixdfsi
.libdsp__fixdfsi:
	 movel	__libdsp__fixdfsi, a0
	jmp	a0@

