.TH SNDCOMPRESS 1 "August 13, 1990" "NeXT Computer, Inc."
.SH NAME
sndcompress \- compress or decompress a soundfile
.SH SYNOPSIS
.B sndcompress [ -<n> ] \fIinputFile\fR \fIoutputFile\fR
.SH DESCRIPTION
\fISndcompress\fR
compresses or decompresses a soundfile.  If the input soundfile is in a
16 bit linear format, it is compressed.  If the input soundfile is in a
compressed format, it is decompressed.  The option controls the compression
type; by default, bit-faithful compression is performed.  With bit-faithful
compression, the decompression operation reproduces the original sound
exactly.
.SH OPTIONS
.TP
.B \-<n>
This option controls the compression amount for non-bit-faithful compression.
Specify as an integer 4 <= n <= 8.  Higher numbers give greater compression.
.SH "SEE ALSO"
sndplay(1), sndrecord(1), sndinfo(1), sndconvert(1)

