.TH SNDINFO 1 "August 13, 1990" "NeXT Computer, Inc."
.SH NAME
sndinfo \- displays soundfile headers on standard output.
.SH SYNOPSIS
.B sndinfo \fIfile\fR ...
.SH DESCRIPTION
\fISndinfo\fR
reads each file in sequence and displays the header
information on standard output.
.SH "SEE ALSO"
sndplay(1), sndrecord(1), sndconvert(1), sndcompress(1)

